networks/models.py
# project/networks/models.py
from project import db
from project.devices.models import Device


class Network(db.Model):
    __tablename__ = 'network'

    id = db.Column(db.Integer, primary_key=True)
    address = db.Column(db.String(32))
    network_id = db.Column(db.String(64))
    reserved_id = db.Column(db.Integer, db.ForeignKey('office.id'))
    device_id = db.Column(db.Integer, db.ForeignKey('device.id'))

    # If IP is connected to a device, return string representation of the hostname of the device the IP is connected to.
    # This is useful for displaying hostnames in tags next to the IP on the Network and Office Info pages
    def __repr__(self):
        if self.device_id != None:
            device = Device.query.get(self.device_id)
            hostname = device.hostname
        return f"{hostname}"

    # Create network data for our JSON endpoint
    @property
    def serialize(self):
        """Return object data in easily serializeable format"""
        if self.network_id == 1:
            office_group = 'Accounting'
        elif self.network_id == 2:
            office_group = 'IT'
        elif self.network_id == 3:
            office_group = 'Administration'
        elif self.network_id == 4:
            office_group = 'CEO'
        elif self.network_id == 5:
            office_group = 'Developers'
        else:
            office_group = 'IP is not part of an office group'

        if self.device_id is not None:
            device = Device.query.get(self.device_id)
            hostname = device.hostname
        else:
            hostname = 'IP currently is not associated with a device'
        return {
            'address': self.address,
            'office_group': office_group,
            'host_device': hostname
        }

networks/forms.py
# project/networks/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField
from wtforms.validators import DataRequired


class AllocateIP(FlaskForm):

    allocate_ip = SelectField(validators=[DataRequired()], coerce=int)
    submit = SubmitField(
        'Allocate IP'
    )

networks/__init__.py
# PROJECT/NETWORKS/__init__.py
from flask import Blueprint

networks_blueprint = Blueprint('networks', __name__,
                     template_folder='templates/networks')
from project.networks import views, models

networks/views.py
# PROJECT/NETWORK/VIEWS.PY
from project.networks import networks_blueprint
from flask import render_template, request, current_app, flash, redirect, url_for, jsonify
from project import db
from project.office.models import Office
from project.networks.models import Network
from project.devices.models import Device
from project.networks.forms import AllocateIP
from flask_login import login_required


@networks_blueprint.route('/network_home')
def network_home():
    return render_template('network_home.html')

@networks_blueprint.route('/ip_address/<ip_address>/JSON/')
def single_ip_json(ip_address):
    ip = Network.query.filter_by(address=ip_address).first()
    return jsonify(Network=[ip.serialize])


@networks_blueprint.route('/csf_networks')
def csf_networks():
    page = request.args.get('page', 1, type=int)
    ip_addresses = Network.query.paginate(page, current_app.config.get('ADDRESSES_PER_PAGE'), False)
    return render_template('networks.html', ip_addresses=ip_addresses)


@networks_blueprint.route('/71_network')
def seventy_one_net():
    page = request.args.get('page', 1, type=int)
    ip_addresses = Network.query.filter(Network.address.like("%10.0.71.%")).order_by(Network.id.asc()). \
        paginate(page, current_app.config.get('ADDRESSES_PER_PAGE'), False)
    return render_template('71_network.html', ip_addresses=ip_addresses)


@networks_blueprint.route('/71_network/JSON')
def seventy_one_net_json():
    ip_addresses = Network.query.filter(Network.address.like("%10.0.71.%")).order_by(Network.id.asc())
    return jsonify(Network=[i.serialize for i in ip_addresses])

@networks_blueprint.route('/72_network')
def seventy_two_net():
    page = request.args.get('page', 1, type=int)
    ip_addresses = Network.query.filter(Network.address.like("%10.0.72.%")).order_by(Network.id.asc()). \
        paginate(page, current_app.config.get('ADDRESSES_PER_PAGE'), False)
    return render_template('72_network.html', ip_addresses=ip_addresses)

@networks_blueprint.route('/72_network/JSON')
def seventy_two_net_json():
    ip_addresses = Network.query.filter(Network.address.like("%10.0.72.%")).order_by(Network.id.asc())
    return jsonify(Network=[i.serialize for i in ip_addresses])


@networks_blueprint.route('/73_network')
def seventy_three_net():
    page = request.args.get('page', 1, type=int)
    ip_addresses = Network.query.filter(Network.address.like("%10.0.73.%")).order_by(Network.id.asc()). \
        paginate(page, current_app.config.get('ADDRESSES_PER_PAGE'), False)
    return render_template('73_network.html', ip_addresses=ip_addresses)

@networks_blueprint.route('/73_network/JSON')
def seventy_three_net_json():
    ip_addresses = Network.query.filter(Network.address.like("%10.0.73.%")).order_by(Network.id.asc())
    return jsonify(Network=[i.serialize for i in ip_addresses])

@networks_blueprint.route('/74_network')
def seventy_four_net():


    page = request.args.get('page', 1, type=int)
    ip_addresses = Network.query.filter(Network.address.like("%10.0.74.%")).order_by(Network.id.asc()). \
        paginate(page, current_app.config.get('ADDRESSES_PER_PAGE'), False)
    return render_template('74_network.html', ip_addresses=ip_addresses)

@networks_blueprint.route('/74_network/JSON')
def seventy_four_net_json():
    ip_addresses = Network.query.filter(Network.address.like("%10.0.74.%")).order_by(Network.id.asc())
    return jsonify(Network=[i.serialize for i in ip_addresses])


@networks_blueprint.route('/75_network')
def seventy_five_net():
    page = request.args.get('page', 1, type=int)
    ip_addresses = Network.query.filter(Network.address.like("%10.0.75.%")).order_by(Network.id.asc()). \
        paginate(page, current_app.config.get('ADDRESSES_PER_PAGE'), False)
    return render_template('75_network.html', ip_addresses=ip_addresses)


@networks_blueprint.route('/allocate_ip/<int:ip_id>', methods=['GET', 'POST'])
@login_required
def allocate_ip(ip_id):
    ip_address = Network.query.filter_by(id=ip_id).first_or_404()
    form = AllocateIP()
    form.allocate_ip.choices = [(row.id, row.hostname) for row in
                               Device.query.order_by(Device.id.asc())]
    if form.validate_on_submit():
        ip_address.device_id = form.allocate_ip.data
        db.session.commit()
        flash("IP Added")
        return redirect(url_for('devices.device',
                                device_id=form.allocate_ip.data,
                                ip_address=ip_address))
    return render_template('allocate_ip.html', form=form,
                           ip_address=ip_address)

networks/templates/networks/71_network.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">71 Network IPs</h1>
            <hr class="my-4">
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="container">
    {% for ip in ip_addresses.items %}
        {% if ip.reserved_id == 1  and ip.device_id != None %}
        <h4 id="E175">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Embraer E175') }}"><span class="badge badge-secondary">E175 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 1  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Embraer E175') }}"><span class="badge badge-secondary"> E175 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 2  and ip.device_id != None %}
        <h4 id="B737">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Boeing 737 MAX') }}"><span class="badge badge-secondary"> B737 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 2  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Boeing 737 MAX') }}"><span class="badge badge-secondary"> B737 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 3  and ip.device_id != None %}
        <h4 id="S76">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Sikorsky S-76') }}"><span class="badge badge-secondary"> S-76 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 3  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Sikorsky S-76') }}"><span class="badge badge-secondary"> S-76 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 4  and ip.device_id != None %}
        <h4 id="A320">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Airbus A320') }}"><span class="badge badge-secondary"> A320 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 4  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Airbus A320') }}"><span class="badge badge-secondary"> A320 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 5  and ip.device_id != None %}
        <h4 id="B777">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Boeing 777') }}"><span class="badge badge-secondary"> B777 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 5  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Boeing 777') }}"><span class="badge badge-secondary"> B777 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 6  and ip.device_id != None %}
        <h4 id="C172">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Redbird Cessna 172') }}"><span class="badge badge-secondary"> C172 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 6  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Redbird Cessna 172') }}"><span class="badge badge-secondary"> C172 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 7  and ip.device_id != None %}
        <h4 id="MJ">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Microjet') }}"><span class="badge badge-secondary"> MJ Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 7  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Microjet') }}"><span class="badge badge-secondary"> MJ Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 8  and ip.device_id != None %}
        <h4 id="KingAir">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Redbird King Air') }}"><span class="badge badge-secondary"> KingAir Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 8  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Redbird King Air') }}"><span class="badge badge-secondary"> KingAir Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == None  and ip.device_id != None %}
        <h4>{{ ip.address }}
            <a href="#"><span class="badge badge-secondary"> Unreserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == None  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href=""><span class="badge badge-secondary"> Unreserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% else %}
        <h4>{{ ip.address }}
            <span class="badge badge-warning">Uncategorized IP</span>
        </h4>
        {% endif %}
    {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% for page_num in ip_addresses.iter_pages(left_edge=1, right_edge=1, left_current=4, right_current=4) %}
          {% if page_num %}
            {% if ip_addresses.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{ url_for('networks.seventy_one_net', page=page_num) }}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('networks.seventy_one_net', page=page_num) }}">{{ page_num }}</a>
                </li>
            {% endif %}
          {% else %}
              ...
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
</div>
{% endblock content %}

networks/templates/networks/72_network.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">72 Network IPs</h1>
            <hr class="my-4">
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="container">
    {% for ip in ip_addresses.items %}
        {% if ip.reserved_id == 1  and ip.device_id != None %}
        <h4 id="E175">{{ ip.address }}
            <span class="badge badge-secondary"><a href="{{ url_for('simulators.sim_info', sim_name='Embraer E175') }}">E175 Reserved IP</a></span>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 1  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Embraer E175') }}"><span class="badge badge-secondary"> E175 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 2  and ip.device_id != None %}
        <h4 id="B737">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Boeing 737 MAX') }}"><span class="badge badge-secondary"> B737 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 2  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Boeing 737 MAX') }}"><span class="badge badge-secondary"> B737 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 3  and ip.device_id != None %}
        <h4 id="S76">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Sikorsky S-76') }}"><span class="badge badge-secondary"> S-76 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 3  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Sikorsky S-76') }}"><span class="badge badge-secondary"> S-76 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 4  and ip.device_id != None %}
        <h4 id="A320">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Airbus A320') }}"><span class="badge badge-secondary"> A320 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 4  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Airbus A320') }}"><span class="badge badge-secondary"> A320 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 5  and ip.device_id != None %}
        <h4 id="B777">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Boeing 777') }}"><span class="badge badge-secondary"> B777 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 5  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Boeing 777') }}"><span class="badge badge-secondary"> B777 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 6  and ip.device_id != None %}
        <h4 id="C172">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Redbird Cessna 172') }}"><span class="badge badge-secondary"> C172 Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 6  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Redbird Cessna 172') }}"><span class="badge badge-secondary"> C172 Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 7  and ip.device_id != None %}
        <h4 id="MJ">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Microjet') }}"><span class="badge badge-secondary"> MJ Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 7  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Microjet') }}"><span class="badge badge-secondary"> MJ Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == 8  and ip.device_id != None %}
        <h4 id="KingAir">{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Redbird King Air') }}"><span class="badge badge-secondary"> KingAir Reserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == 8  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href="{{ url_for('simulators.sim_info', sim_name='Redbird King Air') }}"><span class="badge badge-secondary"> KingAir Reserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% elif ip.reserved_id == None  and ip.device_id != None %}
        <h4>{{ ip.address }}
            <a href="#"><span class="badge badge-secondary"> Unreserved IP</span></a>
            <a href="{{ url_for('devices.device', device_id=ip.device_id) }}"><span class="badge badge-danger">{{ip}}</span></a>
        </h4>
        {% elif ip.reserved_id == None  and ip.device_id == None and (ip.id >= 277 and ip.id <= 306) %}
        <h4>{{ ip.address }}
            <span class="badge badge-info">DHCP</span>
        </h4>
        {% elif ip.reserved_id == None  and ip.device_id == None%}
        <h4>{{ ip.address }}
            <a href=""><span class="badge badge-secondary"> Unreserved IP</span></a>
            <a href="{{ url_for('networks.allocate_ip', ip_id=ip.id) }}"><span class="badge badge-success">IP Available</span></a>
        </h4>
        {% else %}
        <h4>{{ ip.address }}
            <span class="badge badge-warning">Uncategorized IP</span>
        </h4>
        {% endif %}
    {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% for page_num in ip_addresses.iter_pages(left_edge=1, right_edge=1, left_current=4, right_current=4) %}
          {% if page_num %}
            {% if ip_addresses.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{ url_for('networks.seventy_two_net', page=page_num) }}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('networks.seventy_two_net', page=page_num) }}">{{ page_num }}</a>
                </li>
            {% endif %}
          {% else %}
              ...
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
</div>
{% endblock content %}

networks/templates/networks/allocate_ip.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
        <h1 class="display-4">Add IP To Server
        </h1>
        <hr class="my-4">
    </div>
</div>

<div class="container-fluid">
    <form method="POST">
        <label>Choose Server You Would Like to Allocate {{ ip_address.address }} to:</label>
        {{ form.hidden_tag() }}
        {{ form.allocate_ip(class="form-control") }}
        {{ form.submit(class="btn btn-primary btn-sm add-ip-button") }}
    </form>
</div>
{% endblock content %}

networks/templates/networks/network_home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
      <h1 class="display-4">Network Home</h1>
      <p class="lead">Building 201 FAA William J. Hughes Technical Center</p>
      <hr class="my-4">
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                  <div class="card-header card-head-color">
                    71 Network
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">View the 71 Network IP Addresses</h5>
                    <a href="{{ url_for('networks.seventy_one_net') }}" class="btn btn-primary btn-sm">71 Net Info</a>
                  </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                  <div class="card-header card-head-color">
                    72 Network
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">View the 72 Network IP Addresses</h5>
                    <a href="{{ url_for('networks.seventy_two_net') }}" class="btn btn-primary btn-sm">72 Net Info</a>
                  </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card card-divider">
                  <div class="card-header card-head-color">
                    73 Network
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">View the 73 Network IP Addresses</h5>
                    <a href="{{ url_for('networks.seventy_three_net') }}" class="btn btn-primary btn-sm">73 Net Info</a>
                  </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card card-divider">
                  <div class="card-header card-head-color">
                    74 Network
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">View the 74 Network IP Addresses</h5>
                    <a href="{{ url_for('networks.seventy_four_net') }}" class="btn btn-primary btn-sm">74 Net Info</a>
                  </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card card-divider">
                  <div class="card-header card-head-color">
                    75 Network
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">View the 75 Network IP Addresses</h5>
                    <a href="{{ url_for('networks.seventy_five_net') }}" class="btn btn-primary btn-sm">75 Net Info</a>
                  </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

networks/templates/networks/networks.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
        <h1 class="display-4">Network IPs</h1>
        <hr class="my-4">
    </div>
</div>
<div class="container-fluid">
    <div class="container">
    {% for ip in ip_addresses.items %}
        <h4>{{ ip.address }}</h4>
    {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% for page_num in ip_addresses.iter_pages(left_edge=1, right_edge=1, left_current=4, right_current=4) %}
          {% if page_num %}
            {% if ip_addresses.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{ url_for('networks.csf_networks', page=page_num) }}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('networks.csf_networks', page=page_num) }}">{{ page_num }}</a>
                </li>
            {% endif %}
          {% else %}
              ...
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
</div>
{% endblock content %}